#!/usr/bin/env python3
"""Run counterfactual probes on a robot program and print the report.

Usage:
    python scripts/probe_program.py output/program_22_3.py
    python scripts/probe_program.py output/program_300_1.py --robot franka --k 16 --seed 42

Probes execute the program in dry-run mode against ``k`` perturbed scenes
generated by ``architect.probes.scene_mutator`` and report:

  * Static-audit flags (hardcoded poses, joint replays, indexed marker
    accesses, absolute-after-relative ee moves).
  * Per-axis pass-rate (program ran to completion under the perturbation).
  * Names that were permissively stubbed because the program called helpers
    not present in the dry-run namespace and not in the (empty) skill
    library — these are the helpers a future graduation gate would need
    to admit before this program can be considered self-contained.

Exit code is 0 if pass_rate >= ``--threshold`` (default 0.7), else 1, so
this script can be wired into CI for regression-checking the library.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Allow running from project root without install.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from architect.probes.probe_runner import ProbeReport, run_probes
from architect.probes.scene_mutator import default_scene


def _format_audit_flags(report: ProbeReport) -> str:
    if not report.audit_flags:
        return "  (no audit flags)"
    lines = []
    sev_order = {"high": 0, "medium": 1, "low": 2}
    flags = sorted(report.audit_flags, key=lambda f: (sev_order.get(f.severity, 99), f.line))
    for f in flags:
        lines.append(f"  [{f.severity:6s}] line {f.line:>3} {f.kind}: {f.snippet}")
        lines.append(f"           → {f.message}")
    return "\n".join(lines)


def _format_outcomes(report: ProbeReport) -> str:
    lines = []
    for i, o in enumerate(report.outcomes):
        marker = "✓" if o.passed else "✗"
        suffix = "" if o.passed else f" [{o.error_type}: {o.error}]"
        lines.append(f"  {marker} {i:>2}  {o.axis:<22s}{suffix}")
    return "\n".join(lines)


def _format_per_axis(report: ProbeReport) -> str:
    rows = report.per_axis_pass_rate
    lines = []
    for axis, (passed, total) in sorted(rows.items()):
        rate = passed / total if total else 0.0
        lines.append(f"  {axis:<22s} {passed:>2}/{total:<2}  ({rate:.0%})")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("program", type=Path, help="Path to a .py program to probe.")
    parser.add_argument("--robot", default="franka", choices=("franka",),
                        help="Robot whose default scene to use as the probe base.")
    parser.add_argument("--k", type=int, default=16,
                        help="Number of probes to run (default: 16).")
    parser.add_argument("--seed", type=int, default=None,
                        help="RNG seed for reproducible probe suites.")
    parser.add_argument("--threshold", type=float, default=0.7,
                        help="Pass-rate threshold for exit code 0 (default: 0.7).")
    parser.add_argument("--show-outcomes", action="store_true",
                        help="Print one line per probe with the mutation axis and error if any.")
    args = parser.parse_args()

    if not args.program.is_file():
        print(f"error: {args.program} not found", file=sys.stderr)
        sys.exit(2)

    program = args.program.read_text()

    report = run_probes(
        program,
        base_scene=default_scene(args.robot),
        robot_name=args.robot,
        k=args.k,
        seed=args.seed,
    )

    sev = report.audit_severity()

    print(f"\nProbe report for {args.program}  (robot={args.robot}, k={args.k})")
    print("─" * 72)

    print(f"\nAudit flags:  high={sev['high']}  medium={sev['medium']}  low={sev['low']}")
    print(_format_audit_flags(report))

    print(f"\nProbe pass-rate:  {report.n_passed}/{report.k}  ({report.pass_rate:.0%})")
    print("\nPer-axis pass-rate:")
    print(_format_per_axis(report))

    if args.show_outcomes:
        print("\nPer-probe outcomes:")
        print(_format_outcomes(report))

    if report.stubbed_names:
        print(f"\nStubbed (helpers not in namespace, called {len(report.stubbed_names)} unique):")
        for n in report.stubbed_names:
            print(f"  - {n}")

    print()
    sys.exit(0 if report.pass_rate >= args.threshold else 1)


if __name__ == "__main__":
    main()
